name: 'Upload to AWS S3 using Docker'
description: 'Upload using docker action'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'Region s3 bucket'
    required: true
  dist-folder:
    description: 'The folder containing deployable files'
    required: true
outputs:
  website-url:
    description: 'the url of deployed website'
runs:
  using: 'docker'
  image: 'Dcokerfile'